# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true

# Debug mode, only for development. Is overwritten by ${SEARXNG_DEBUG}
debug: false
# displayed name
instance_name: "Private SearXNG Instance"
# For example: https://example.com/privacy
privacypolicy_url: false
# use true to use your own donation page written in searx/info/en/donate.md
# use false to disable the donation link
donation_url: false
# mailto:contact@example.com
contact_url: false
# record stats
enable_metrics: true

search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 0
  # Existing autocomplete backends: "dbpedia", "duckduckgo", "google", "yandex",
  # "seznam", "startpage", "swisscows", "qwant", "wikipedia" - leave blank to turn it off
  # by default.
  autocomplete: "duckduckgo"
  # minimun characters to type before autocompleter starts
  autocomplete_min: 4
  # Default search language - leave blank to detect from browser information or
  # use codes from 'languages.py'
  default_lang: "all"
  # Available languages
  # languages:
  #   - all
  #   - en
  #   - en-US
  #   - de
  #   - it-IT
  #   - fr
  #   - fr-BE
  # ban time in seconds after engine errors
  ban_time_on_fail: 5
  # max ban time in seconds after engine errors
  max_ban_time_on_fail: 120
  suspended_times:
    # Engine suspension time after error (in seconds; set to 0 to disable)
    # For error "Access denied" and "HTTP error [402, 403]"
    SearxEngineAccessDenied: 86400
    # For error "CAPTCHA"
    SearxEngineCaptcha: 86400
    # For error "Too many request" and "HTTP error 429"
    SearxEngineTooManyRequests: 3600
    # Cloudflare CAPTCHA
    cf_SearxEngineCaptcha: 1296000
    cf_SearxEngineAccessDenied: 86400
    # ReCAPTCHA
    recaptcha_SearxEngineCaptcha: 604800

  # remove 369t to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html
    - csv
    - json
    - rss

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "436b72544f8391b7da56e599c5edb63a6c76d1d55790b8bb64bb66d87519d329"  # change this!
  limiter: false  # can be disabled for a private instance
  image_proxy: true
  # 1.0 and 1.1 are supported
  http_protocol_version: "1.0"
  method: "GET"

redis:
  url: redis://redis:6379/0

ui:
  static_use_hash: true
  theme_args:
    # style of simple theme: auto, light, dark
    simple_style: dark


engines:
  - name: 9gag
    disabled: true

  - name: annas archive
    disabled: true

  - name: apk mirror
    disabled: true

  - name: apple app store
    disabled: true

  - name: ahmia
    disabled: true

  - name: anaconda
    disabled: true

  - name: arch linux wiki
    disabled: true

  - name: artic
    disabled: true

  - name: arxiv
    disabled: true

  - name: ask
    disabled: true

  - name: bandcamp
    disabled: true

  - name: wikipedia
    disabled: true

  - name: bilibili
    disabled: true

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: bing images
    disabled: true

  - name: bing news
    disabled: true

  - name: bing videos
    disabled: true

  - name: bitbucket
    disabled: true

  - name: bpb
    disabled: true

  - name: btdigg
    disabled: true

  - name: openverse
    disabled: true

  - name: media.ccc.de
    disabled: true

  - name: chefkoch
    disabled: true

  - name: cppreference
    disabled: true

  - name: crossref
    disabled: true

  - name: crowdview
    disabled: true

  - name: yep
    disabled: true

  - name: yep images
    disabled: true

  - name: yep news
    disabled: true

  - name: curlie
    disabled: true

  - name: currency
    disabled: true

  - name: bahnhof
    disabled: true

  - name: deezer
    disabled: true

  - name: destatis
    disabled: true

  - name: deviantart
    disabled: true

  - name: ddg definitions
    disabled: true

  - name: docker hub
    disabled: true

  - name: erowid
    disabled: true

  - name: wikidata
    disabled: true

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: duckduckgo images
    disabled: true

  - name: duckduckgo videos
    disabled: true

  - name: duckduckgo news
    disabled: true

  - name: duckduckgo weather
    disabled: true

  - name: apple maps
    disabled: true

  - name: emojipedia
    disabled: true

  - name: tineye
    disabled: true

  - name: etymonline
    disabled: true

  - name: 1x
    disabled: true

  - name: fdroid
    disabled: true

  - name: flickr
    disabled: true

  - name: free software directory
    disabled: true

  - name: frinkiac
    disabled: true

  - name: fyyd
    disabled: true

  - name: genius
    disabled: true

  - name: gentoo
    disabled: true

  - name: gitlab
    disabled: true

  - name: github
    disabled: true

  - name: codeberg
    disabled: true

  - name: goodreads
    disabled: true

  - name: google
    engine: google
    shortcut: go
    disabled: false

  - name: google images
    disabled: true

  - name: google news
    disabled: true

  - name: google videos
    disabled: true

  - name: google scholar
    disabled: true

  - name: google play apps
    disabled: true

  - name: google play movies
    disabled: true

  - name: material icons
    disabled: true

  - name: gpodder
    disabled: true

  - name: habrahabr
    disabled: true

  - name: hackernews
    disabled: true

  - name: hex
    disabled: true

  - name: hoogle
    disabled: true

  - name: imdb
    disabled: true

  - name: imgur
    disabled: true

  - name: ina
    disabled: true

  - name: invidious
    disabled: true

  - name: jisho
    disabled: true

  - name: kickass
    disabled: true

  - name: lemmy communities
    disabled: true

  - name: lemmy users
    disabled: true

  - name: lemmy posts
    disabled: true

  - name: lemmy comments
    disabled: true

  - name: library genesis
    disabled: true

  - name: z-library
    disabled: true

  - name: library of congress
    disabled: true

  - name: libretranslate
    disabled: true

  - name: lingva
    disabled: true

  - name: lobste.rs
    disabled: true

  - name: mastodon users
    disabled: true

  - name: mastodon hashtags
    disabled: true

  - name: mdn
    disabled: true

  - name: metacpan
    disabled: true

  - name: mixcloud
    disabled: true

  - name: mozhi
    disabled: true

  - name: mwmbl
    disabled: true

  - name: npm
    disabled: true

  - name: nyaa
    disabled: true

  - name: mankier
    disabled: true

  - name: odysee
    disabled: true

  - name: openairedatasets
    disabled: true

  - name: openairepublications
    disabled: true

  - name: openmeteo
    disabled: true

  - name: openstreetmap
    disabled: true

  - name: openrepos
    disabled: true

  - name: packagist
    disabled: true

  - name: pdbe
    disabled: true

  - name: photon
    disabled: true

  - name: pinterest
    disabled: true

  - name: piped
    disabled: true

  - name: piped.music
    disabled: true

  - name: piratebay
    disabled: true

  - name: pixiv
    disabled: true

  - name: podcastindex
    disabled: true

  - name: presearch
    disabled: true

  - name: presearch images
    disabled: true

  - name: presearch videos
    disabled: true

  - name: presearch news
    disabled: true

  - name: pub.dev
    disabled: true

  - name: pubmed
    disabled: true

  - name: pypi
    disabled: true

  - name: qwant
    disabled: true

  - name: qwant news
    disabled: true

  - name: qwant images
    disabled: true

  - name: qwant videos
    disabled: true

  - name: radio browser
    disabled: true

  - name: reddit
    disabled: true

  - name: rottentomatoes
    disabled: true

  - name: searchmysite
    disabled: true

  - name: sepiasearch
    disabled: true

  - name: soundcloud
    disabled: true

  - name: stackoverflow
    disabled: true

  - name: askubuntu
    disabled: true

  - name: internetarchivescholar
    disabled: true

  - name: superuser
    disabled: true

  - name: searchcode code
    disabled: true

  - name: semantic scholar
    disabled: true

  - name: startpage
    disabled: true

  - name: tokyotoshokan
    disabled: true

  - name: solidtorrents
    disabled: true

  - name: tagesschau
    disabled: true

  - name: tmdb
    disabled: true

  - name: torch
    disabled: true

  - name: unsplash
    disabled: true

  - name: yandex music
    disabled: true

  - name: yahoo
    engine: yahoo
    shortcut: yh
    disabled: false

  - name: yahoo news
    disabled: true

  - name: youtube
    disabled: true

  - name: dailymotion
    disabled: true

  - name: vimeo
    disabled: true

  - name: wiby
    disabled: false

  - name: alexandria
    disabled: true

  - name: wikibooks
    disabled: true

  - name: wikinews
    disabled: true

  - name: wikiquote
    disabled: true

  - name: wikisource
    disabled: true

  - name: wikispecies
    disabled: true

  - name: wiktionary
    disabled: true

  - name: wikiversity
    disabled: true

  - name: wikivoyage
    disabled: true

  - name: wikicommons.images
    disabled: true

  - name: wikicommons.videos
    disabled: true

  - name: wikicommons.audio
    disabled: true

  - name: wikicommons.files
    disabled: true

  - name: wolframalpha
    disabled: true

  - name: dictzone
    disabled: true

  - name: mymemory translated
    disabled: true

  - name: 1337x
    disabled: true

  - name: duden
    disabled: true

  - name: seznam
    disabled: true

  - name: mojeek
    disabled: true

  - name: moviepilot
    disabled: true

  - name: naver
    disabled: true

  - name: rubygems
    disabled: true

  - name: peertube
    disabled: true

  - name: mediathekviewweb
    disabled: true

  - name: yacy
    disabled: true

  - name: yacy images
    disabled: true

  - name: rumble
    disabled: true

  - name: livespace
    disabled: true

  - name: wordnik
    disabled: true

  - name: woxikon.de synonyme
    disabled: true

  - name: seekr news
    disabled: true

  - name: seekr images
    disabled: true

  - name: seekr videos
    disabled: true

  - name: sjp.pwn
    disabled: true

  - name: stract
    disabled: true

  - name: svgrepo
    disabled: true

  - name: tootfinder
    disabled: true

  - name: voidlinux
    disabled: true

  - name: wallhaven
    disabled: true

  - name: wikimini
    disabled: true

  - name: wttr.in
    disabled: true

  - name: yummly
    disabled: true

  - name: brave
    disabled: true

  - name: brave.images
    disabled: true

  - name: brave.videos
    disabled: true

  - name: brave.news
    disabled: true

  - name: lib.rs
    disabled: true

  - name: sourcehut
    disabled: true

  - name: goo
    disabled: true

  - name: bt4g
    disabled: true

  - name: pkg.go.dev
    disabled: true
